name = "Just Optimized"
author = "bs2kbs2k"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e625cc96824ff9f9ea3616a21d6d48cb0b6bc938fa70cd29ea6046f0e4838066"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
