name = "Just Optimized"
author = "bs2kbs2k"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cfe9a28f83c9f3e0a0b9d838219ebf850ae7871bb4e57d7f782c1a42f2fc084"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"
