name = "Just Optimized"
author = "bs2kbs2k"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae65a3608bc370a03f7354e1c3b50e42064596f1dc018500b47c9cac7a087e13"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
