name = "Just Optimized"
author = "bs2kbs2k"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdb16b6e7c000c6520627a0d0e907a8f875ed7d4a1671117412d94bece62181e"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"
